from dotenv import load_dotenv
import os

load_dotenv()

MLFLOW_TRACKING_URI=os.getenv("MLFLOW_TRACKING_URI")
MLFLOW_S3_ENDPOINT_URL=os.getenv("MLFLOW_S3_ENDPOINT_URL")
MLFLOW_BID_PRICE_EXP = os.getenv("MLFLOW_BID_PRICE_EXP")
MLFLOW_VOLATILITY_EXP = os.getenv("MLFLOW_VOLATILITY_EXP")

MINIO_USER_ID=os.getenv("MINIO_USER_ID")
MINIO_PASSWORD=os.getenv("MINIO_PASSWORD")

AWS_DEFAULT_REGION = os.getenv("AWS_DEFAULT_REGION")